version: '3'

services:
  server:
    build:
      context: server/python
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  db:
    image: postgis/postgis:14-3.2
    #ports:
    #  - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data